### ISSUE TITLE
Array#comprehension fails on Rubinius.

### ISSUE THREAD

**Issue by postmodern** [postmodern/combinatorics#1]
`Array#comprehension` specs fail on Rubinius.

```
1)
NotImplementedError in 'Array#comprehension should yield iterations to the given block'
no continuation support
kernel/common/enumerator.rb:52:in `next'
kernel/bootstrap/array.rb:85:in `map'
kernel/bootstrap/array.rb:66:in `each'
kernel/bootstrap/array.rb:85:in `map'
kernel/common/enumerator.rb:15:in `each'
kernel/common/enumerable.rb:817:in `to_a'
./spec/list_comprehension_spec.rb:15:in `__script__'
kernel/common/eval.rb:159:in `instance_eval'
/home/hal/src/ruby/rubinius/lib/timeout.rb:134:in `timeout'
kernel/bootstrap/array.rb:66:in `each'
kernel/bootstrap/array.rb:66:in `each'
kernel/delta/codeloader.rb:67:in `load_script'
kernel/delta/codeloader.rb:91:in `load_script'
kernel/loader.rb:460:in `script'
kernel/loader.rb:571:in `main'
kernel/loader.rb:609:in `main'
kernel/loader.rb:621:in `__script__'

2)
NotImplementedError in 'Array#comprehension should do nothing an Array of all non-enumerable objects'
no continuation support
kernel/common/enumerator.rb:52:in `next'
kernel/bootstrap/array.rb:85:in `map'
kernel/bootstrap/array.rb:66:in `each'
kernel/bootstrap/array.rb:85:in `map'
kernel/common/enumerator.rb:15:in `each'
kernel/common/enumerable.rb:817:in `to_a'
./spec/list_comprehension_spec.rb:21:in `__script__'
kernel/common/eval.rb:159:in `instance_eval'
/home/hal/src/ruby/rubinius/lib/timeout.rb:134:in `timeout'
kernel/bootstrap/array.rb:66:in `each'
kernel/bootstrap/array.rb:66:in `each'
kernel/delta/codeloader.rb:67:in `load_script'
kernel/delta/codeloader.rb:91:in `load_script'
kernel/loader.rb:460:in `script'
kernel/loader.rb:571:in `main'
kernel/loader.rb:609:in `main'
kernel/loader.rb:621:in `__script__'

3)
NotImplementedError in 'Array#comprehension should iterate over the values within an enumerable value'
no continuation support
kernel/common/enumerator.rb:52:in `next'
kernel/bootstrap/array.rb:85:in `map'
kernel/bootstrap/array.rb:66:in `each'
kernel/bootstrap/array.rb:85:in `map'
kernel/common/enumerator.rb:15:in `each'
kernel/common/enumerable.rb:817:in `to_a'
./spec/list_comprehension_spec.rb:34:in `__script__'
kernel/common/eval.rb:159:in `instance_eval'
/home/hal/src/ruby/rubinius/lib/timeout.rb:134:in `timeout'
kernel/bootstrap/array.rb:66:in `each'
kernel/bootstrap/array.rb:66:in `each'
kernel/delta/codeloader.rb:67:in `load_script'
kernel/delta/codeloader.rb:91:in `load_script'
kernel/loader.rb:460:in `script'
kernel/loader.rb:571:in `main'
kernel/loader.rb:609:in `main'
kernel/loader.rb:621:in `__script__'

4)
NotImplementedError in 'Array#comprehension should ignore non-enumerable values'
no continuation support
kernel/common/enumerator.rb:52:in `next'
kernel/bootstrap/array.rb:85:in `map'
kernel/bootstrap/array.rb:66:in `each'
kernel/bootstrap/array.rb:85:in `map'
kernel/common/enumerator.rb:15:in `each'
kernel/common/enumerable.rb:817:in `to_a'
./spec/list_comprehension_spec.rb:41:in `__script__'
kernel/common/eval.rb:159:in `instance_eval'
/home/hal/src/ruby/rubinius/lib/timeout.rb:134:in `timeout'
kernel/bootstrap/array.rb:66:in `each'
kernel/bootstrap/array.rb:66:in `each'
kernel/delta/codeloader.rb:67:in `load_script'
kernel/delta/codeloader.rb:91:in `load_script'
kernel/loader.rb:460:in `script'
kernel/loader.rb:571:in `main'
kernel/loader.rb:609:in `main'
kernel/loader.rb:621:in `__script__'
```

**Comment by postmodern** [comment]
No longer supporting Rubinius.
